[package]
name = "wasi_pyrb_diff_test"
version = "0.1.0"
edition = "2021"

[dependencies]
docker-api = "0.14.0"
futures = "0.3.30"
tokio = "1.38.0"
lazy_static = "1.4.0"
rayon = "1.10.0"
regex = "1.10.3"
rustc-hash = "1.1.0"
